config/routes.rb
Rails.application.routes.draw do
  resources :users

  root to: 'main#index', as: :main
  post 'users/validate' => 'users#validate', as: :users_validation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to main_path
    else
      render :new
    end
  end

  def validate
    user = User.new(user_params)
    user.valid?
    field = params[:user].first[0]
    @errors = user.errors[field]

    if @errors.empty?
      @errors = true
    else
      @errors
    end

    respond_to do |format|
      format.json { render json: @errors }
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QpardTestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1> Welcome </h1>
<%= button_to 'Click it!', new_user_path, method: :get %>

app/views/users/new.html.erb
<%= bootstrap_form_for(@user) do |f| %>
    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>
    <%= f.email_field :email %>
    <%= f.password_field :password %>
    <%= f.submit "Sign Up!" %>
<% end %>